### ISSUE TITLE
Question :  Access OCR information ? 

### ISSUE THREAD

**Issue by cruxm4n** [floh22/LeagueOCR#1]

**Comment by floh22** [comment]
Hey! This project is very much a work in project and not yet complete. I will be updating it in the following days.

For now however the information gathered can be accessed under
http://localhost:3002/api/objectives
http://localhost:3002/api/teams

I will update the repo with a readme and instructions once the project is further along

**Comment by floh22** [comment]
To close up this issue, I have finally finished updating this to actually function **somewhat** usably.
The endpoints provided by this program are the same as before:
http://localhost:3002/api/objectives
http://localhost:3002/api/teams

However, the information is now properly filled and in a json format, so for anyone that wants to use the pure OCR information, I would consider this project in a functional, though rather untested state, so any feedback in regards to issues is very appreciated. I will be adding a build soon to make actually using this a bit easier.
